spring:
  application:
    name: CONFIG-DEFAULT

eureka:
  instance:
    appname: CONFIG-DEFAULT
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka



